blank_issues_enabled: false
pull_request_templates:
  - name: ğŸ› ä¸å…·åˆä¿®æ­£
    description: ãƒã‚°ä¿®æ­£ç”¨ã®ãƒ†ãƒ³ãƒ—ãƒ¬ãƒ¼ãƒˆã§ã™
    file: bugfix.md
  - name: âœ¨ æ©Ÿèƒ½è¿½åŠ 
    description: æ–°æ©Ÿèƒ½ã®è¿½åŠ ã«ä½¿ã†ãƒ†ãƒ³ãƒ—ãƒ¬ãƒ¼ãƒˆã§ã™
    file: feature.md
  - name: default
    file: pull_request_template.md
