blank_issues_enabled: false
pulls:
  - name: ğŸ› ä¸å…·åˆä¿®æ­£ç”¨
    description: ãƒã‚°ä¿®æ­£ã‚’è¡Œã†ãŸã‚ã®ãƒ†ãƒ³ãƒ—ãƒ¬ãƒ¼ãƒˆ
    file: bugfix.md
  - name: âœ¨ æ©Ÿèƒ½è¿½åŠ ç”¨
    description: æ–°ã—ã„æ©Ÿèƒ½ã‚’è¿½åŠ ã™ã‚‹ãŸã‚ã®ãƒ†ãƒ³ãƒ—ãƒ¬ãƒ¼ãƒˆ
    file: feature.md
